import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";

import { parseAuthCookie, verifyToken } from "@/app/utils/jwt";
import { redirect } from "next/navigation";

import { AppSidebar } from "@/components/app-sidebar"
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar.jsx";
import { ModalDataProvider } from "@/app/(authenticated)/home/context.js";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Dignum",
    description: "Generated by create next app",
};

export default async function RootLayout({children}) {
    const headersList = await headers();
    const token = parseAuthCookie(headersList.get('cookie'));
    const payload = token ? verifyToken(token) : null;

    if (!payload) {
        redirect('/login');
    }

    return (
        <SidebarProvider style={{ "--sidebar-width": "calc(var(--spacing) * 72)", "--header-height": "calc(var(--spacing) * 12)", }}>
            <AppSidebar variant="inset" />
            <ModalDataProvider>
                {children}
            </ModalDataProvider>
        </SidebarProvider>
    );
}
