import '@/app/resources/app.scss';

import { Geist, Geist_Mono } from "next/font/google";
import Navigation from "@/components/navigation/navigation.component";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Dignum",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="de">
            <head>
                <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
                <title>{metadata.title}</title>
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
             <div className='layout'>
                 <Navigation />
                 {children}
             </div>
            </body>
        </html>
    );
}
