import '@/app/resources/app.scss';

import { Geist, Geist_Mono } from "next/font/google";
import { headers } from "next/headers";
import Navigation from "@/components/navigation/navigation.component";
import { parseAuthCookie, verifyToken } from "@/app/utils/jwt";
import { redirect } from "next/navigation";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Dignum",
    description: "Generated by create next app",
};

export default async function RootLayout({children}) {
    const headersList = await headers();
    const token = parseAuthCookie(headersList.get('cookie'));
    const payload = token ? verifyToken(token) : null;

    if (!payload) {
        redirect('/login');
    }

    return (
        <html lang="de">
            <head>
                <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
                <title>{metadata.title}</title>
            </head>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
             <div className='layout'>
                 <Navigation payload={payload} />
                 {children}
             </div>
            </body>
        </html>
    );
}
